# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Laboratory for Advanced Manufacturing and Finishing Processes
email: koushik@iisc.ac.in
description: > # this means to ignore newlines until "baseurl:"
  The Laboratory for Advanced Manufacturing and Finishing Processes (LAMFP) at IISc studies problems at the interface of mechanics, physics and materials science with applications in manufacturing and materials processing. The lab has three primary thrust areas:
1) Novel cutting and forming based processes
2) Processing mechanics of soft materials (elastomers, natural materials)
3) High-performance finishing processes

We address both fundamental scientific problems as well as design and development of machine tools and mechanisms. 
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

